language: rust
cache: cargo
dist: trusty
sudo: false
rust:
  - stable

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - |
      cargo build &&
      cargo build --release &&
      cargo test &&
      cargo test --release &&
      cargo bench &&
      cargo doc
